swagger: "2.0"
info:
  title: Godking Restapi for Testing
  description: version 1 for testing
  version: 1.0.0
  contact:
    email: zhou_jing_king@hotmail.com
basePath: /api/v1
paths:
  /person/{id}:
    get:
      tags:
      - person
      description: Get person information by id
      parameters:
      - in: path
        name: id
        description: the id of person
        required: true
        type: integer
        format: int64
      - in: query
        name: name
        description: the name
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Person'
        "400":
          description: bad request
        "404":
          description: not found
definitions:
  models.Person:
    title: Person
    type: object
    properties:
      age:
        type: integer
        format: int64
      id:
        type: string
      name:
        type: string
      title:
        type: string
tags:
- name: person
  description: |
    Person API for testing
